messages:
   prefix: "[\u00a7aCustomRTP]" # plugin prefix
   rtp: "Teleport..." # Message to rtp
   rtp_sucess: "Youre teleported to coordinats" # if rtp sucess
   rtp_error: "You are not teleported because a suitable location was not found"
   rtp_dont_permission: "You dont have permission to use this!"
location:
   radius: 
      x_min: 0
      z_min: 0
      x_max: 1000
      z_max: 1000
   world: "world"